shell /usr/bin/arch -arm64 /bin/zsh
env TERM xterm-256color

font_family      JetBrainsMono Nerd Font
font_size        14.0

initial_window_width  123c
initial_window_height 32c

background         #282828

tab_bar_style      hidden

confirm_os_window_close 0

map cmd+c         copy_to_clipboard
map cmd+v         paste_from_clipboard

url_style         curly
open_url_with     default

scrollback_lines  10000
